# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/project_set/vivado_projects/PCC/scc/scc.srcs/sources_1/ip/scc/scc.xci
# IP: The module: 'scc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project_set/vivado_projects/PCC/scc/scc.srcs/sources_1/ip/scc/scc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: f:/project_set/vivado_projects/PCC/scc/scc.srcs/sources_1/ip/scc/scc.xci
# IP: The module: 'scc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/project_set/vivado_projects/PCC/scc/scc.srcs/sources_1/ip/scc/scc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'scc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
